### ISSUE TITLE
How to use Angular Template Syntax inside alerts

### ISSUE THREAD

**Issue by lippomano** [toverux/ngx-sweetalert2#16]
Is it possible to put a list into html?
Something like this:

  ```
<ul>
    <li *ngFor="let hero of heroes">
      {{ hero }}
    </li>
  </ul>
```
I need to show list as the text of the swal, this is what I do:

```
swal({
        title: 'title',
        type: 'error',
        html: '<ul><li *ngFor="let err of messageErr">{{err}}</li></ul>'
      });
```
But It seems that don't evaluate {{ err }}
![cattura](https://user-images.githubusercontent.com/27501745/28968335-cbe62f74-791f-11e7-8fad-5285db81da1d.PNG)

**Comment by toverux** [comment]
Unfortunately, no, this is not possible for now.

You can effectively pass HTML via the `html` option, but this must be normal, standard HTML. You are using the Angular template syntax here.
I cannot either parse it using the Angular Compiler before passing it to SweetAlert2, because production builds of Angular do not embed the JiT compiler.

The solution I see would be to use a template or transclusion, but both require an update of ngsweetalert2.

I will add that to my todo list, but I'm afraid you have to find another solution for now.
I suggest you to programmatically generate a string containing your list, and pass that HTML string to SweetAlert2.

**Comment by toverux** [comment]
Did some research over time and still don't know if that's actually possible.
If someone knows how to do that, (s)he's welcome!

**Comment by shayts** [comment]
I had the same problem and eventually did the following:

<span id="rangePicker" style="display: none">
    <span id="innerRangePicker">
        <div class="row">
            <app-datetime-range-picker [inline]= "true" [toMaxDate]="maxDate" [fromValue]="fromTime" (valueChange)="onRangePickerValueChange($event)"></app-datetime-range-picker>
        </div>
        
        <div class="row video-format-row">
            <div class="col-3 video-format-col">
                <select class="form-control" [(ngModel)]="selectedVideoFormat">
                    <option value='3'>mp4</option>
                    <option value='2'>avi</option>
                </select>
            </div>
        </div>
    </span>
</span>


swal({
            title: "some title",
            html: '<span id="swalSpan"></span>',
            showCancelButton: true,
            onOpen: function (val) {
                let spanList = val.getElementsByTagName("span");
                let swalSpan: HTMLElement;

                for (let i = 0; i < spanList.length; i++) {
                    if (spanList[i].id === "swalSpan") {
                        swalSpan = spanList[i];
                        break;
                    }
                }

                let picker = document.getElementById('innerRangePicker');
                swalSpan.appendChild(picker);
            },
            onClose: function () {
                let picker = document.getElementById('innerRangePicker');
                let pickerHolder = document.getElementById('rangePicker');

                pickerHolder.appendChild(picker);
            }
        });


I'm not sure if this is the best solution but that is the best I could think of.
Maybe it can help someone with a similar problem.

**Comment by toverux** [comment]
Good news! This is now possible with the v.3 release! https://github.com/toverux/ngx-sweetalert2/releases/tag/v3.0.0
Beware that the package changed name (everything is explained in the release notes).

**Comment by behroozbc** [comment]
how can I use `<br>` in text property ?

**Comment by toverux** [comment]
You cannot, you have to use `[html]="Hello<br>World"` for that. SweetAlert2 does not allow HTML "by default" to avoid security vulnerabilities, if, for example, your alerts display user-defined content.

The original option property `html` is documented here: https://sweetalert2.github.io/#configuration
Supported by ngx-sweetalert2 with the `[html]` @Input() here: https://github.com/sweetalert2/ngx-sweetalert2/blob/master/src/swal.component.ts#L34

You can also use the `*swalPartial` directive for more complex use cases and templates, it is documented here: https://github.com/sweetalert2/ngx-sweetalert2#swalpartialdirective

**Comment by jongbonga** [comment]
Hi 

I'm not using the ngx-sweetalert2 but rather the normal Swal (main) sweetalert2.
and would like to know if it's possible to achieve what this thread is about?

Basically I would like have something like

```
Swal.fire({
    title: 'RATE YOUR ORDER',
    html: `<bar-rating [max]="5" [theme]="'stars'"></bar-rating>`,
    showCloseButton: true
});
```

**Comment by toverux** [comment]
You can't without this library :)

**Comment by jongbonga** [comment]
@toverux thanks ! I appreciate
