### ISSUE TITLE
Cancel button triggers confirm

### ISSUE THREAD

**Issue by JustinLutsky** [toverux/ngx-sweetalert2#36]
I think this just started happening after a recent update. Seems that the confirm function triggers even when clicking cancel or dismissing the modal. I don't think this was happening a few weeks ago when I first started using ngx-sweetalert2. Here's one example of the code:

` <i *ngIf="store.isActive" [swal]="{title: 'Deactivate Store', text: store.storeName, type: 'question', showCancelButton: true}"
          (confirm)="toggleActive(store, false)" class="fa fa-2x fa-power-off text-success ml-1" placement="top" ngbTooltip="Deactivate"></i>`

**Comment by toverux** [comment]
@JustinLutsky why have you closed the issue?

**Comment by JustinLutsky** [comment]
I think I posted a bit prematurely. The next thing I did was update to version 3, changed my import statement, and everything was working again.

**Comment by toverux** [comment]
Okay :) What happened to you can be easily explained if you upgraded sweetalert2 to v7 before upgrading ngx-sweetalert2 to v3.
