### ISSUE TITLE
Angular5 update?

### ISSUE THREAD

**Issue by vanhullc** [toverux/ngx-sweetalert2#38]
The module does not seem to work on the angular 5 version, any update planed? Don't want to recode every dialogs haha

EDITED : My bad, working fine --'

**Comment by NoCodeNoMore** [comment]
@vanhullc have you tried to delete node_modules and remove the packages related to sweetalert from config and ran `npm install --save sweetalert2 @toverux/ngx-sweetalert2` again? 

I see that some packages are from 4.x but for me it seems to work currently.

**Comment by vanhullc** [comment]
Oh yeah sorry for that working fine now ^^'

**Comment by toverux** [comment]
> I see that some packages are from 4.x but for me it seems to work currently.

Yes, Angular 5 is not officially supported for now (that should come soon), but it should work flawlessly :)
