### ISSUE TITLE
simple swalPartial directive not working

### ISSUE THREAD

**Issue by tavuntu** [toverux/ngx-sweetalert2#44]
I'm trying to show an alert using the swalPartial directive, but it's empty and it should be showing the label "how are you?" as content, or maybe I'm missing something? (take a look at app/app.component.html)

here's a minimal repo reproducing the issue: https://bitbucket.org/tavuntu/testswal

just run `npm i` and `ng serve`

maybe it has something to do with [this](https://github.com/toverux/ngx-sweetalert2/issues/39)? (I'm using Angular CLI  1.5.4.)

**Comment by tavuntu** [comment]
nevermind, I see this is the same issue. Unlike the other targets, the content target is not getting replaced, right?

**Comment by toverux** [comment]
> Unlike the other targets, the content target is not getting replaced, right?
Yep :)

Here's a workaround : https://github.com/toverux/ngx-sweetalert2/issues/39#issuecomment-346867816

Please subscribe to the other issue in order to get an update when this is fixed, just in case I forget to ping you here.

**Comment by tavuntu** [comment]
this plugin is awesome, btw, keep the awesome work!
